= The Trouble with Troubleshooting
Write the Docs Australia 2019 Lightning Talk

This is the source for a Lightning Talk I gave to the Write the Docs Australia 2019 conference about troubleshooting info in manuals.

== Watch It

You can watch this on the Write the Docs Australia YouTube feed once the video is live.

== Build It

For the tooling setup, follow the bundle or NPM pre-req's https://github.com/asciidoctor/asciidoctor-reveal.js/#prerequisites

I chose Bundler for this presentation because it works really cleanly.
Install ruby and bundler according to the instructions at https://asciidoctor.org/docs/asciidoctor-revealjs/#prerequisites

If you want to build this presentation, run
`# bundle exec asciidoctor-revealjs trouble-with-troubleshooting.adoc` to build it to html.

== Print It

If you want to print out this presentation in PDF form, add `?print_pdf` to the end of the `trouble-with-troubleshooting.html` file when you load it in your browser to get a continuous page feed of the slides.

You can then use any browser PDF converter (like Google's Print to PDF) to get a copy of the slides.

== License
